apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-webfront
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-webfront
  template:
    metadata:
      labels:
        app: react-webfront
    spec:
      containers:
      - name: react-webfront
        image: harinadh14/react_frontend_encry_working:latest
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-logs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-logs
      version: appsignals
  template:
    metadata:
      labels:
        app: java-logs
        version: appsignals
    spec:
      containers:
      - name: java-logs
        image: harinadh14/maven_spring_working_mongosever:app-signals
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
